# arxivの学問領域の指定
subject: 'cat:astro-ph.*'

# 検索キーワード
keywords:
        Europa: 4
        Ganymede: 4
        Callisto: 4
        Enceladus: 4
        Titan: 3
        Triton: 3
        Icy: 3
        ocean: 2
        plume: 3
        radar: 3
        Jupiter: 2

# 通知の閾値
score_threshold: 4
